### ISSUE TITLE
try to create a consolidated list of errors

### ISSUE THREAD

**Issue by hn-88** [hn-88/OpenSpace-AppleSiliconMac#34]
Absolutely! Here is a script that will:

1. **Parse `compile_commands.json`** (which CMake creates when you set `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`).
2. **Compile each file individually** with its specific flags.
3. **Continue compiling even if some files fail.**
4. **Aggregate all errors** into a single log.

This approach is robust: it uses the exact flags CMake would use for each file, so it works even with complex per-file options, defines, and include paths.

---

```bash name=compile_all_from_compile_commands.sh
#!/usr/bin/env bash
set -euo pipefail

# Directory containing compile_commands.json
BUILD_DIR="${1:-build}"
OUTPUT_DIR="${2:-individual_build}"
COMPILE_COMMANDS="$BUILD_DIR/compile_commands.json"

if [ ! -f "$COMPILE_COMMANDS" ]; then
    echo "Error: $COMPILE_COMMANDS not found. Make sure you run cmake with -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

ERROR_LOG="$OUTPUT_DIR/compile_errors.txt"
: > "$ERROR_LOG"

echo "Parsing compile_commands.json and compiling each file individually..."

# Parse JSON: for each entry, get 'file' and 'command'
# This works on macOS with jq installed (brew install jq)
COUNT=0
FAIL_COUNT=0

jq -c '.[]' "$COMPILE_COMMANDS" | while read -r entry; do
    SRC_FILE=$(echo "$entry" | jq -r '.file')
    COMMAND=$(echo "$entry" | jq -r '.command')

    # Output object file to OUTPUT_DIR instead of original output
    # Remove the -o <file> and replace with our own
    OBJ_FILE="$OUTPUT_DIR/$(basename "${SRC_FILE%.*}").o"
    CUSTOM_COMMAND=$(echo "$COMMAND" | sed -E "s/-o [^ ]+/-o \"$OBJ_FILE\"/")

    echo "Compiling $SRC_FILE"
    if ! eval "$CUSTOM_COMMAND" 2>>"$ERROR_LOG"; then
        echo "FAILED: $SRC_FILE" >> "$ERROR_LOG"
        ((FAIL_COUNT++))
    fi
    ((COUNT++))
done

echo "Compilation finished. $COUNT files processed. $FAIL_COUNT file(s) failed."
if (( FAIL_COUNT > 0 )); then
    echo "See $ERROR_LOG for details."
    exit 1
else
    echo "All files compiled successfully."
fi
```

---

## How to Use

1. **Configure your CMake build with:**
   ```bash
   cmake -G Xcode -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ...
   ```
   This ensures `compile_commands.json` will be present in the build directory.

2. **Add this step to your GitHub Actions workflow, after configuring CMake:**
   ```yaml
   - name: Custom individual file compilation
     run: |
       brew install jq
       chmod +x compile_all_from_compile_commands.sh
       ./compile_all_from_compile_commands.sh "$HOME/source/OpenSpace/build" "$HOME/source/OpenSpace/individual_build" || true
       cat "$HOME/source/OpenSpace/individual_build/compile_errors.txt"
   - name: Upload compile error log
     if: failure()
     uses: actions/upload-artifact@v4
     with:
       name: individual-compile-errors
       path: $HOME/source/OpenSpace/individual_build/compile_errors.txt
   ```

---

## Notes

- **jq** is required for JSON parsing (`brew install jq`).
- All per-file flags, includes, and defines are respected.
- This process **does not link**: it only checks that each translation unit compiles.
- Errors are aggregated in `compile_errors.txt`.
- Great for catching all syntax/compilation errors in large, complex CMake projects.

---

Let me know if you want this script as a file for your repo, or if you need further customization!

**Comment by hn-88** [comment]
```yaml name=.github/workflows/consolidated_errors_with_compiledb.yml
name: consolidated-errors-arm64

on: workflow_dispatch

env:
  BUILD_TYPE: Release
  OPENSPACE_VERSION: "0.21.0post-rc1"
  THIS_REPO_PATH: "/Users/runner/work/OpenSpace-AppleSiliconMac/OpenSpace-AppleSiliconMac" 

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    
    - name: get openspace code for a particular release
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        git clone --recursive https://github.com/hn-88/OpenSpace.git "$openSpaceHome"
        cd "$openSpaceHome"
        git checkout ToCompileOnMacOS --recurse-submodules
        mkdir build
        cd build

    - name: Update Homebrew and Install GLM, jq, Python
      run: |
        brew update
        brew install glm jq python

    - name: Install compiledb (Python tool)
      run: |
        pip3 install compiledb

    - name: get patched Ghoul
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        cd "$openSpaceHome/ext"
        rm -rf ghoul
        git clone https://github.com/hn-88/Ghoul.git --branch MacOSfixes --recursive

    - name: patch touchbar
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        # cp -v src-interaction-touchbar.mm "$openSpaceHome/src/interaction/touchbar.mm"

    - name: patch verifier.inl and other files
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        # cp -v include-openspace-documentation-verifier.inl "$openSpaceHome/include/openspace/documentation/verifier.inl"
        # cp -v modules-webgui-webguimodule.cpp "$openSpaceHome/modules/webgui/webguimodule.cpp"
        # cp -v modules-webbrowser-webbrowsermodule.cpp "$openSpaceHome/modules/webbrowser/webbrowsermodule.cpp"
        # cp -v ext-json-CMakeLists.txt "$openSpaceHome/ext/json/CMakeLists.txt"
        # cp -v src-documentation-verifier.cpp "$openSpaceHome/src/documentation/verifier.cpp"
        # cp -v modules-webbrowser-src-cefhost.cpp "$openSpaceHome/modules/webbrowser/src/cefhost.cpp"
        # cp -v include-openspace-util-json_helper.inl "$openSpaceHome/include/openspace/util/json_helper.inl"
    
    - name: Install dependencies
      run: |
        brew install glew boost freeimage mpv vulkan-headers vulkan-loader brotli gdal qt@6

    - name: Configure CMake (Xcode generator)
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        cd "$openSpaceHome/build"
        cmake -G Xcode -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_CXX_STANDARD=20 -DONLY_ACTIVE_ARCH=YES -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 ..

    - name: Generate compile_commands.json using compiledb
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        cd "$openSpaceHome/build"
        compiledb -p .

    - name: Custom individual file compilation
      run: |
        brew install jq
        chmod +x compile_all_from_compile_commands.sh
        ./compile_all_from_compile_commands.sh "$HOME/source/OpenSpace/build" "$HOME/source/OpenSpace/individual_build" || true
        cat "$HOME/source/OpenSpace/individual_build/compile_errors.txt"
        
    - name: Upload compile error log
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: individual-compile-errors
        path: $HOME/source/OpenSpace/individual_build/compile_errors.txt
```
**Key changes:**
- Added a step to install `compiledb` via pip.
- Added a step to run `compiledb -p .` in the build directory right after CMake generates the Xcode project.
- Everything else remains the same, so your custom compile scripts will now find `compile_commands.json` as expected.
